export const projects = [
  { id:'ryfio', number:'01', title:'Ryfio', marketingTitle:'TURNING IDEAS INTO PRODUCTS.', tag:'AI COMMERCE · INTERNATIONAL', category:'E-commerce · AI', description:'Plateforme e-commerce et print-on-demand qui transforme une idée en produit personnalisable avec une expérience assistée par IA.', url:'https://www.ryfio.com/', image:'/projects/screens/ryfio.webp', mobileImage:'/projects/screens/mobile/ryfio.webp', accent:'dark' },
  { id:'tian-tian-wang', number:'02', title:'Tian Tian Wang', marketingTitle:'A DIGITAL TASTE OF THE EXPERIENCE.', tag:'RESTAURANT · PARIS', category:'Web design · Development', description:'Expérience web immersive pour un restaurant du Sichuan, avec identité forte, menu, galerie et parcours de réservation.', url:'https://tiantian-jo6d.vercel.app/', image:'/projects/screens/tian-tian-wang.webp', mobileImage:'/projects/screens/mobile/tian-tian-wang.webp', accent:'orange' },
  { id:'agilregra', number:'03', title:'Agilregra Construção', marketingTitle:'BUILT AS SOLID AS THEIR WORK.', tag:'CONSTRUCTION · ÎLE-DE-FRANCE', category:'Web design · Construction', description:'Site vitrine orienté conversion pour une entreprise de construction, avec services, réalisations et demandes de devis.', url:'https://altiketo.vercel.app/', image:'/projects/screens/agilregra.webp', mobileImage:'/projects/screens/mobile/agilregra.webp', accent:'blue' },
  { id:'prospect', number:'04', title:'Prospect', marketingTitle:'FROM SEARCH TO LEAD. FASTER.', tag:'SAAS · PROSPECTION', category:'Product · SaaS', description:'Application de prospection pour trouver des entreprises locales, filtrer les leads et centraliser les contacts commerciaux.', url:'https://prospect-umber.vercel.app/', image:'/projects/screens/prospect.webp', mobileImage:'/projects/screens/mobile/prospect.webp', accent:'blue' },
  { id:'cecile', number:'05', title:'Cécile', marketingTitle:'CLEAN BUSINESS. STRONG PRESENCE.', tag:'NETTOYAGE · LUNEL', category:'Web design · Services', description:'Site premium pour une activité de nettoyage, pensé pour rendre l’offre immédiatement lisible et générer des demandes de devis.', url:'https://c-cile.vercel.app/', image:'/projects/screens/cecile.webp', mobileImage:'/projects/screens/mobile/cecile.webp', accent:'green' },
  { id:'dm-maconnerie', number:'06', title:'D.M. Maçonnerie', marketingTitle:'CRAFT BUILT TO LAST.', tag:'MAÇONNERIE · FRANCE', category:'Web design · Artisan', description:'Identité web chaleureuse et haut de gamme pour une entreprise de maçonnerie, avec mise en avant du savoir-faire et des réalisations.', url:'', image:'/projects/screens/dm-maconnerie.webp', mobileImage:'/projects/screens/mobile/dm-maconnerie.webp', accent:'orange' },
  { id:'remed-peinture', number:'07', title:'Remed Peinture', marketingTitle:'A FINISH THAT STANDS OUT.', tag:'PEINTURE · RENNES', category:'Web design · Artisan', description:'Direction éditoriale minimaliste pour un peintre à Rennes, avec une forte hiérarchie visuelle et un accès rapide aux réalisations.', url:'https://peinte-g4au.vercel.app/', image:'/projects/screens/remed-peinture.webp', mobileImage:'/projects/screens/mobile/remed-peinture.webp', accent:'green' }
];
